services:
  bot:
    build: .
    container_name: telegram-langbot
    depends_on:
      - libretranslate
      - db
    env_file:
      - ./.env
      
    networks:
      - botnet
  db:
    image: postgres:16-alpine
    container_name: langbot-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - botnet
 
  libretranslate:
    image: libretranslate/libretranslate:v1.8.3
    container_name: libretranslate
    command:
      - --load-only
      - en,es,fr,de,it,ja
      - --threads
      - "4"
      - --debug
    ports:
      - "5000:5000"
    volumes:
      - libretranslate-data:/home/libretranslate/.local
    restart: unless-stopped
    networks:
      - botnet
    dns:
      - 1.1.1.1
      - 8.8.8.8





networks:
  botnet:
    driver: bridge

volumes:
  db_data:
  libretranslate-data: